// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdveitaixecydvvyvigo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdmVpdGFpeGVjeWR2dnl2aWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzk0NzAsImV4cCI6MjA2NTU1NTQ3MH0.E505Bvj6kIyJbkJGgrAGM1ts-fnysxiL43b-_cIt0ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);